language: julia
os: linux
julia: 1.4

env:
  - BUILDTYPE=releases
  - BUILDTYPE=nightly

branches:
  only: master

services: docker

script:
    - export BUILDROOT=$PWD/pdf/build && mkdir $BUILDROOT
    - export JULIA_SOURCE=$PWD/pdf/build/julia &&
      git clone https://github.com/JuliaLang/julia.git $JULIA_SOURCE
    - export JULIA_DOCS=$PWD/pdf/build/docs.julialang.org &&
      git clone https://github.com/JuliaLang/docs.julialang.org.git -b assets --single-branch $JULIA_DOCS
    - julia --color=yes pdf/make.jl ${BUILDTYPE}
    - julia --color=yes pdf/make.jl commit
